server:
  port: 9002
  
spring:
  application:
    name: product-service
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/products_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: sql@2019#!
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

keycloak:
  realm: formation-ms
  auth-server-url: http://localhost:8080/auth
  resource: product-app
  credentials:
    secret: c26f6a42-e294-4387-81e3-2aa457949441
  principal-attribute: preferred_username
  bearer-only: true

swagger-ui:
  client: swagger-ui
  secret: 38cc945e-dc12-4e96-af5b-8569d6dc0125

eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: test
  datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: sa
        driver-class-name: org.h2.Driver
  jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate :
          ddl-auto: create

eureka:
  client:
    enabled: false