server:
  port: 9001
  
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/sales_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: sql@2019#!
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

keycloak:
  realm: formation-ms
  auth-server-url: http://localhost:8080/auth
  resource: sales-app
  credentials:
    secret: 287e769d-abee-45e1-b5db-190be79f08dc
  principal-attribute: preferred_username
  bearer-only: true

swagger-ui:
  client: sales-app-swagger-ui
  secret: aec4fb5a-ff66-46cc-afda-1c74de9405cc

eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/