server:
  port: 8765

spring: 
  application:
    name: zuul-server

eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  routes:
    clients:
      path: /manage-clients/**
      serviceId: client-service
    sales:
      path: /manage-sales/**
      serviceId: sales-service
    products:
      path: /manage-products/**
      serviceId: product-service
  sensitive-headers: Cookie, Set-Cookie
    